/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as PressRouteImport } from './routes/press'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CinematicRouteImport } from './routes/cinematic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as DebateIndexRouteImport } from './routes/debate.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MemberSignupRouteImport } from './routes/member.signup'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberLoginRouteImport } from './routes/member.login'
import { Route as MemberLeaderboardRouteImport } from './routes/member.leaderboard'
import { Route as MemberDashboardRouteImport } from './routes/member.dashboard'
import { Route as MemberChallengeRouteImport } from './routes/member.challenge'
import { Route as DebateTopicIdRouteImport } from './routes/debate.$topicId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPressRouteImport } from './routes/admin.press'
import { Route as AdminPageMediaRouteImport } from './routes/admin.page-media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminContactLinksRouteImport } from './routes/admin.contact-links'
import { Route as AdminCharactersRouteImport } from './routes/admin.characters'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicRoute = CinematicRouteImport.update({
  id: '/cinematic',
  path: '/cinematic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateIndexRoute = DebateIndexRouteImport.update({
  id: '/debate/',
  path: '/debate/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSignupRoute = MemberSignupRouteImport.update({
  id: '/member/signup',
  path: '/member/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/member/profile',
  path: '/member/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/member/login',
  path: '/member/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLeaderboardRoute = MemberLeaderboardRouteImport.update({
  id: '/member/leaderboard',
  path: '/member/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/member/dashboard',
  path: '/member/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberChallengeRoute = MemberChallengeRouteImport.update({
  id: '/member/challenge',
  path: '/member/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateTopicIdRoute = DebateTopicIdRouteImport.update({
  id: '/debate/$topicId',
  path: '/debate/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPressRoute = AdminPressRouteImport.update({
  id: '/admin/press',
  path: '/admin/press',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPageMediaRoute = AdminPageMediaRouteImport.update({
  id: '/admin/page-media',
  path: '/admin/page-media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactLinksRoute = AdminContactLinksRouteImport.update({
  id: '/admin/contact-links',
  path: '/admin/contact-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCharactersRoute = AdminCharactersRouteImport.update({
  id: '/admin/characters',
  path: '/admin/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic': typeof CinematicRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/contact-links': typeof AdminContactLinksRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/page-media': typeof AdminPageMediaRoute
  '/admin/press': typeof AdminPressRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/debate/$topicId': typeof DebateTopicIdRoute
  '/member/challenge': typeof MemberChallengeRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/leaderboard': typeof MemberLeaderboardRoute
  '/member/login': typeof MemberLoginRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/signup': typeof MemberSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/debate/': typeof DebateIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic': typeof CinematicRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/contact-links': typeof AdminContactLinksRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/page-media': typeof AdminPageMediaRoute
  '/admin/press': typeof AdminPressRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/debate/$topicId': typeof DebateTopicIdRoute
  '/member/challenge': typeof MemberChallengeRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/leaderboard': typeof MemberLeaderboardRoute
  '/member/login': typeof MemberLoginRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/signup': typeof MemberSignupRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/debate': typeof DebateIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cinematic': typeof CinematicRoute
  '/contact': typeof ContactRoute
  '/press': typeof PressRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/contact-links': typeof AdminContactLinksRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/page-media': typeof AdminPageMediaRoute
  '/admin/press': typeof AdminPressRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/debate/$topicId': typeof DebateTopicIdRoute
  '/member/challenge': typeof MemberChallengeRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/leaderboard': typeof MemberLeaderboardRoute
  '/member/login': typeof MemberLoginRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/signup': typeof MemberSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/debate/': typeof DebateIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cinematic'
    | '/contact'
    | '/press'
    | '/testimonials'
    | '/admin/books'
    | '/admin/characters'
    | '/admin/contact-links'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/page-media'
    | '/admin/press'
    | '/admin/profile'
    | '/admin/setup'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/books/$bookId'
    | '/debate/$topicId'
    | '/member/challenge'
    | '/member/dashboard'
    | '/member/leaderboard'
    | '/member/login'
    | '/member/profile'
    | '/member/signup'
    | '/admin/'
    | '/books/'
    | '/debate/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cinematic'
    | '/contact'
    | '/press'
    | '/testimonials'
    | '/admin/books'
    | '/admin/characters'
    | '/admin/contact-links'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/page-media'
    | '/admin/press'
    | '/admin/profile'
    | '/admin/setup'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/books/$bookId'
    | '/debate/$topicId'
    | '/member/challenge'
    | '/member/dashboard'
    | '/member/leaderboard'
    | '/member/login'
    | '/member/profile'
    | '/member/signup'
    | '/admin'
    | '/books'
    | '/debate'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cinematic'
    | '/contact'
    | '/press'
    | '/testimonials'
    | '/admin/books'
    | '/admin/characters'
    | '/admin/contact-links'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/page-media'
    | '/admin/press'
    | '/admin/profile'
    | '/admin/setup'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/books/$bookId'
    | '/debate/$topicId'
    | '/member/challenge'
    | '/member/dashboard'
    | '/member/leaderboard'
    | '/member/login'
    | '/member/profile'
    | '/member/signup'
    | '/admin/'
    | '/books/'
    | '/debate/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CinematicRoute: typeof CinematicRoute
  ContactRoute: typeof ContactRoute
  PressRoute: typeof PressRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminCharactersRoute: typeof AdminCharactersRoute
  AdminContactLinksRoute: typeof AdminContactLinksRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPageMediaRoute: typeof AdminPageMediaRoute
  AdminPressRoute: typeof AdminPressRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  DebateTopicIdRoute: typeof DebateTopicIdRoute
  MemberChallengeRoute: typeof MemberChallengeRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberLeaderboardRoute: typeof MemberLeaderboardRoute
  MemberLoginRoute: typeof MemberLoginRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberSignupRoute: typeof MemberSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  DebateIndexRoute: typeof DebateIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematic': {
      id: '/cinematic'
      path: '/cinematic'
      fullPath: '/cinematic'
      preLoaderRoute: typeof CinematicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate/': {
      id: '/debate/'
      path: '/debate'
      fullPath: '/debate/'
      preLoaderRoute: typeof DebateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/signup': {
      id: '/member/signup'
      path: '/member/signup'
      fullPath: '/member/signup'
      preLoaderRoute: typeof MemberSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/member/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/login': {
      id: '/member/login'
      path: '/member/login'
      fullPath: '/member/login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/leaderboard': {
      id: '/member/leaderboard'
      path: '/member/leaderboard'
      fullPath: '/member/leaderboard'
      preLoaderRoute: typeof MemberLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/member/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/challenge': {
      id: '/member/challenge'
      path: '/member/challenge'
      fullPath: '/member/challenge'
      preLoaderRoute: typeof MemberChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate/$topicId': {
      id: '/debate/$topicId'
      path: '/debate/$topicId'
      fullPath: '/debate/$topicId'
      preLoaderRoute: typeof DebateTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/press': {
      id: '/admin/press'
      path: '/admin/press'
      fullPath: '/admin/press'
      preLoaderRoute: typeof AdminPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/page-media': {
      id: '/admin/page-media'
      path: '/admin/page-media'
      fullPath: '/admin/page-media'
      preLoaderRoute: typeof AdminPageMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-links': {
      id: '/admin/contact-links'
      path: '/admin/contact-links'
      fullPath: '/admin/contact-links'
      preLoaderRoute: typeof AdminContactLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/characters': {
      id: '/admin/characters'
      path: '/admin/characters'
      fullPath: '/admin/characters'
      preLoaderRoute: typeof AdminCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CinematicRoute: CinematicRoute,
  ContactRoute: ContactRoute,
  PressRoute: PressRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminCharactersRoute: AdminCharactersRoute,
  AdminContactLinksRoute: AdminContactLinksRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPageMediaRoute: AdminPageMediaRoute,
  AdminPressRoute: AdminPressRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVideosRoute: AdminVideosRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  DebateTopicIdRoute: DebateTopicIdRoute,
  MemberChallengeRoute: MemberChallengeRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberLeaderboardRoute: MemberLeaderboardRoute,
  MemberLoginRoute: MemberLoginRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberSignupRoute: MemberSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  DebateIndexRoute: DebateIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
